name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"  # every day
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/TyCoding/langchat.git
          git remote set-url upstream https://github.com/TyCoding/langchat.git || true
          
      - name: Fetch upstream
        run: |
          git fetch upstream main
          
      - name: Backup local files
        run: |
          mkdir -p .backup
          # 备份可能发生冲突的文件
          cp -f langchat-server/src/main/resources/application-dev.yml .backup/ || true
          cp -f langchat-ui/pnpm-lock.yaml .backup/ || true
          cp -r .github/workflows .backup/ || true
          
      - name: Merge upstream
        run: |
          # 使用 ours 策略进行合并，保留上游的更改
          git merge -X theirs upstream/main --no-edit || true
          
          # 恢复本地文件（如果需要）
          if [ -f .backup/application-dev.yml ]; then
            cp -f .backup/application-dev.yml langchat-server/src/main/resources/
          fi
          
          # 恢复工作流文件
          if [ -d .backup/workflows ]; then
            cp -rf .backup/workflows/* .github/workflows/
          fi
          
          # 添加所有更改
          git add .
          
          # 提交更改
          git commit -m "Merge upstream changes and resolve conflicts" || echo "No changes to commit"
          
      - name: Push changes
        run: |
          git push origin main
          
      - name: Cleanup
        run: |
          rm -rf .backup
          
      - name: Check for conflicts
        if: failure()
        run: |
          echo "::warning::Sync encountered conflicts. Some files may need manual review:"
          git status
          # 不立即退出，让用户知道具体哪些文件需要处理
          echo "You may need to manually sync the following files:"
          echo "- langchat-server/src/main/resources/application-dev.yml"
          echo "- langchat-ui/pnpm-lock.yaml"
