name: Upstream Sync

# 更新权限配置
permissions:
  contents: write
  workflows: write  # 添加 workflows 权限

on:
  schedule:
    - cron: "0 0 * * *"  # every day
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Save current workflow
        run: |
          mkdir -p .workflow_backup
          cp .github/workflows/sync-upstream.yml .workflow_backup/ || true
          
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/TyCoding/langchat.git
          git fetch upstream main
          
      - name: Merge upstream
        run: |
          # 尝试合并上游更改
          git merge upstream/main --no-edit || true
          
          # 恢复原始工作流文件
          mkdir -p .github/workflows
          cp -f .workflow_backup/sync-upstream.yml .github/workflows/ || true
          
          # 添加更改
          git add .
          
          # 提交更改
          git commit -m "Merge upstream changes and restore workflow" || echo "No changes to commit"
          
      - name: Push changes
        run: |
          git push origin main
        
      - name: Cleanup
        if: always()
        run: |
          rm -rf .workflow_backup
